ALTER TABLE characters
    ADD COLUMN IF NOT EXISTS health SMALLINT DEFAULT 100 NOT NULL,
    ADD COLUMN IF NOT EXISTS pname TEXT DEFAULT 'Kyle' NOT NULL,
    ADD COLUMN IF NOT EXISTS gold BIGINT DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS appearance INT[3] DEFAULT ARRAY[16734003, 4367253, 1752748] NOT NULL;