ALTER TABLE characters
    ADD COLUMN IF NOT EXISTS health SMALLINT,
    ADD COLUMN IF NOT EXISTS pname TEXT,
    ADD COLUMN IF NOT EXISTS gold BIGINT,
    ADD COLUMN IF NOT EXISTS appearance TEXT[3];